---
driver:
  name: vagrant
  require_chef_omnibus: '12.3.0'
  network:
  - ["private_network", {ip: "192.168.33.101"}]
  customize:
    memory: 1024
    cpus: 2
    cpuexecutioncap: 80

platforms:
  - name: ubuntu-12.04-chef-zero
    provisioner:
      name: chef_zero
    driver:
      box: ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: ubuntu-14.04-chef-zero
    provisioner:
      name: chef_zero
    driver:
      box: ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: debian-7.4-chef-zero
    provisioner:
      name: chef_zero
    driver:
      box: debian-7.4.0
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: centos-6.6-chef-zero
    provisioner:
      name: chef_zero
    driver:
      box: centos-6.6
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
  - name: ubuntu-12.04-chef-solo
    provisioner:
      name: chef_solo
    driver:
      box: ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    run_list:
      - recipe[rvm::system]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: ubuntu-14.04-chef-solo
    provisioner:
      name: chef_solo
    driver:
      box: ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    # run_list:
    #   - recipe[apt::default]
    #   - recipe[curl::default]
    # attributes:
    #   grafana:
    #     webserver_listen: ''
  - name: debian-7.4-chef-solo
    provisioner:
      name: chef_solo
    driver:
      box: debian-7.4.0
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
    # run_list:
    #   - recipe[apt::default]
    #   - recipe[curl::default]
  - name: centos-6.6-chef-solo
    provisioner:
      name: chef_solo
    driver:
      box: centos-6.6
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[dashing::default]
    attributes:
