---
driver:
  name: vagrant
  require_chef_omnibus: '12.3.0'
  network:
  - ["private_network", {ip: "192.168.33.101"}]
  customize:
    memory: 1024
    cpus: 2
    cpuexecutioncap: 80

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: ubuntu-12.04
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: ubuntu-14.04
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: debian-7.8
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: debian-8.1
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: centos-6.7
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3
  - name: centos-7.1
    run_list:
      - recipe[rvm::system]
      - recipe[nodejs::default]
    attributes:
      dashing:
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p551'
      rvm:
        rubies:
          - 1.9.3

suites:
  - name: default
    run_list:
      - recipe[dashing::default]
    attributes:
